### ISSUE TITLE
ncu is confused by the tipex versioning

### ISSUE THREAD

**Issue by bluepuma77** [friendofsvelte/tipex#10]
We are using `ncu` to always use the latest version of libraries, it seems to be confused by the versioning of tipex, on different runs it shows different upgrade paths, depending which version is currently installed.

```
# ncu
 @friendofsvelte/tipex  ^0.0.1-meta-stable.16  →  ^0.0.1-act.4
```

```
# ncu -u -t minor
 @friendofsvelte/tipex  ^0.0.1-act.4  →  ^0.0.1-meta-stable.16
```

**Comment by Bishwas-py** [comment]
The latest version Tipex is `0.0.1-act.4`, I have never used `ncu`, maybe you could guide me with that?

**Comment by bluepuma77** [comment]
`ncu` is a tool that can update all npm dependencies to the latest version.

> Find newer versions of package dependencies than what your package.json allows 
https://github.com/raineorshine/npm-check-updates

You can decide if you want to update major (x.x.x), minor (1.x.x) or only patch (1.1.x).

Usually npm is not updating major, but you might want to update all because the lower version is stale/buggy.

I am using NodeJS since 2011 and only found and started using `ncu` this year 😄

**Comment by Bishwas-py** [comment]
Oh wow, feels like a nice tool. Is the issue fix, man?

**Comment by bluepuma77** [comment]
`ncu` is still confused by `0.0.1-meta-stable.16` and `0.0.1-act.11`. I am still confused, too.

It seems to conform with [Semantic Versioning 2.0.0](https://semver.org/) and Svelte uses similar `5.0.0-next.28`.

I think a working version should get a simple `[v]x.y.z`. Go for `1.0.0` 😃

**Comment by Bishwas-py** [comment]
@bluepuma77 I am releasing a `0.0.2` version I hope that'll help you. Currently, we're in a preview version `0.0.1-prev.0.2`, so that we can test stuff and head over to `0.0.2`. Thanks a lot for you contributions and issues though.

**Comment by Bishwas-py** [comment]
Closing it for now. Please feel free to restart or mention or reopen this issue.
