### ISSUE TITLE
Update HTML content programmatically.

### ISSUE THREAD

**Issue by PacoPerfilan** [friendofsvelte/tipex#14]
Hi! 

I'm trying to update both using user input and also add a variable value when the user clicks a button. There is way to achieve this? I'm accessing the value using the store $tipexEditor.getHTML() method.

**Comment by Bishwas-py** [comment]
Hello!
Can you please clarify `update both using user input`? What do you mean by that?

**Comment by PacoPerfilan** [comment]
Hi! I think I found the solution.

I have the text editor where the types in. Also, I have two buttons that call this function and I was not being able to add the value to the store. This is my current solution. It works at the moment

`   /**
	 * @param {string} fieldPlaceholder
	 */
   function addPlaceholder (fieldPlaceholder){
      if(fieldPlaceholder == "prospect"){
        
        $tipexEditor?.commands.insertContent(" @prospecto ")
      }else if(fieldPlaceholder == "company"){
        
        $tipexEditor?.commands.insertContent(" @empresa ")
      }
   }
   `

**Comment by Bishwas-py** [comment]
Happy to know that.
