### ISSUE TITLE
How to get the HTML out of the editor

### ISSUE THREAD

**Issue by AlloryDante** [friendofsvelte/tipex#15]
Hello, I have the basic component working:
`<Tipex {htmlContent} displayDefaultControls floatingMenu style="margin-top: 1rem; margin-bottom: 0;" className="h-[70vh] border border-neutral-200" />`

I want to make a preview window so I can see how the text looks after it has been edited. I've searched the docs and related issues and I wasnt able to find a method to get the text in a var and display it. So far i've been trying to display {htmlContent} but it seems its static and the var doesnt update when text is entered.

Could someone please help me getting access to a var that is updating while someone types in the editor area? 
Many thanks

Edit: I found this:
```
Try this $tipexEditor.getHTML() to get html.
FYI:
$tipexEditor.getText() -> to get plain text.
$tipexEditor.getJson() -> to get content data in json.
```

**My problem is that I still dont know _how to import $tipexEditor variable_ and this also raised one more question: _How to assign html to typex_ (if I edit htmlContent var with a fetch api the content inside typex still does not change)**

**Comment by AlloryDante** [comment]
I manage to solve all my issues:
1. import {  tipexEditor } from '@friendofsvelte/tipex'; - will allow you to use $tipexEditor.getHTML() to fetch text
2. $tipexEditor?.chain().setContent('Haha').run() - will allow you to overwrite content


**Many thanks to the author of this lib and hopefully we will see more options like text align and many more.**

**Comment by paulhovey** [comment]
I came across this when looking to update the body based on a select dropdown.  Any chance we could make the body parameter bindable?  Then someone could just `bind:body={myHTML}` and update `myHTML` variable to set the body.  Maybe that's not possible to do with tiptap, just an idea.

**Comment by vincent** [comment]
To people looking for a simple `bind` answer, the easiest seems to be a thin wrapper, like so

```ts
// RichText.svelte
<script lang="ts">
  import "@friendofsvelte/tipex/styles/Tipex.css";
  import "@friendofsvelte/tipex/styles/ProseMirror.css";
  import "@friendofsvelte/tipex/styles/Controls.css";
  import "@friendofsvelte/tipex/styles/EditLink.css";
  import "@friendofsvelte/tipex/styles/CodeBlock.css";
  import { Tipex } from '@friendofsvelte/tipex';

  let {
    value = $bindable(),
    size = 50
  } = $props()

  let tipex = $state<any>();
</script>

<Tipex
  body={value}
  bind:tipex
  controls !focal
  class="h-[{size}vh] border border-neutral-200"
  onupdate={() => value = tipex?.getHTML()}
/>
```
