### ISSUE TITLE
Control buttons should have type="button" attribute

### ISSUE THREAD

**Issue by paulando** [friendofsvelte/tipex#16]
I used this text editor component inside <form on:submit|preventDefault={handleFormSubmit}> element and on every editor's button click it automatically submits form. Adding type="button" attribute on every button inside component should fix issue.

**Comment by Bishwas-py** [comment]
I believe it was the old version, the new one already has `type="button"`.

**Comment by Bishwas-py** [comment]
Closing it for now. Please feel free to restart or mention or reopen this issue.
