### ISSUE TITLE
Using PWA without SvelteKit gives error

### ISSUE THREAD

**Issue by lalilaloe** [friendofsvelte/tipex#17]
![image](https://github.com/friendofsvelte/tipex/assets/9057622/c1865d7b-d89d-476d-8c6b-5bea62cb5ff3)

For now I removed the browser check with a patch. In my case I use a PWA with Routify. Maybe another more universal check if the `EditLinkMenu` component is SSR or in the browser will do

**Comment by mzehrer** [comment]
I second this. Using Tipex in a non-sveltekit environment is difficult. I also needed rollup-plugin-node-polyfills in my rollup config to get over the process object.

**Comment by Bishwas-py** [comment]
I will consider about the `EditLinkMenu`? Can I know more about the issue?

**Comment by lalilaloe** [comment]
> I will consider about the `EditLinkMenu`? Can I know more about the issue?

In a svelte project without sveltekit there is no $app environment. So in my patch `tipex/link/EditLinkMenu.svelte`

I removed the browser check;

```diff
-  import { browser } from "$app/environment";
...
-  if (browser && enableLinkEdit) {
+  if (enableLinkEdit) {
     pasteLink();
   }
```

if you want you could replace it with `const is_browser = typeof window !== "undefined";` for example to keep framework agnostic

**Comment by Bishwas-py** [comment]
> @mzehrer  I second this. Using Tipex in a non-sveltekit environment is difficult. I also needed rollup-plugin-node-polyfills in my rollup config to get over the process object.

It should be working now. Can you check and confirm?

**Comment by Bishwas-py** [comment]
Closing this for now, as of the new version, `0.0.7-up-5`. Feel free to reopen this.
