### ISSUE TITLE
Image upload not working

### ISSUE THREAD

**Issue by geoffkendall** [friendofsvelte/tipex#18]
I'm unable to get image dragging and dropping (or copy and pasting) working. When I am dragging an image over my Tipex editor, I see the line indicating where it is going to be dropped, but when I drop the image the browser jumps to showing that image, rather than embedding it into the editor. I found an article that shows how to control what happens when a drop event occurs: https://www.codemzy.com/blog/tiptap-drag-drop-image

But this relies on being able to set TipTap's editorProps when the editor is created, and I can't access that via Tipex. Would it be possible to expose that (like you do with extensions) so I can create my own drag/drop handler?

Thank you!
Geoff

**Comment by Bishwas-py** [comment]
@geoffkendall okay, will have a look at it. I'll be back with that.

**Comment by Bishwas-py** [comment]
@geoffkendall I am not sure, if this would help you or not but
```
 export let onEditorCreate: (editor: Editor) => void = () => {
    };
    export let onEditorDestroy: () => void = () => {
    };
    export let onEditorUpdate: (event: { editor: Editor, transaction: Transaction }) => void = () => {
    };

    onMount(() => {
        if (floatingMenu) {
            extensions['floatingMenu'] = prepareDefaultFloatingMenu(floatingMenuElement);
        }
        $tipexEditor = new Editor({
            element: tipexEditorElement,
            extensions: [
                StarterKit.configure({
                    codeBlock: false
                }),
                ...Object.values(extensions) as Extensions,
            ],
            content: htmlContent as string,
            onTransaction() {
                // force re-render so `editor.isActive` works as expected
                $tipexEditor = $tipexEditor;
            },
            autofocus: true,
            onCreate: ({editor}) => {
                onEditorCreate(editor);
            },
            onDestroy: onEditorDestroy,
            onUpdate: onEditorUpdate
        });
    });
```

Will using `onEditorCreate` do it for you?

**Comment by geoffkendall** [comment]
Thanks Bishwas!On 29 May 2024, at 13:49, Bishwas Bhandari ***@***.***> wrote:﻿
@geoffkendall I am not sure, if this would help you or not but
 export let onEditorCreate: (editor: Editor) => void = () => {
    };
    export let onEditorDestroy: () => void = () => {
    };
    export let onEditorUpdate: (event: { editor: Editor, transaction: Transaction }) => void = () => {
    };

    onMount(() => {
        if (floatingMenu) {
            extensions['floatingMenu'] = prepareDefaultFloatingMenu(floatingMenuElement);
        }
        $tipexEditor = new Editor({
            element: tipexEditorElement,
            extensions: [
                StarterKit.configure({
                    codeBlock: false
                }),
                ...Object.values(extensions) as Extensions,
            ],
            content: htmlContent as string,
            onTransaction() {
                // force re-render so `editor.isActive` works as expected
                $tipexEditor = $tipexEditor;
            },
            autofocus: true,
            onCreate: ({editor}) => {
                onEditorCreate(editor);
            },
            onDestroy: onEditorDestroy,
            onUpdate: onEditorUpdate
        });
    });

Will using onEditorCreate do it for you?

**Comment by geoffkendall** [comment]
Hi @Bishwas-py,
From the article I found, I believe I need to pass a `handleDrop` function to the constructor via editorProps, as follows:

```
new Editor({
  element: tipexEditorElement,
  extensions: [
    StarterKit.configure({
      codeBlock: false
    }),
    ...Object.values(extensions) as Extensions,
  ],
  editorProps: {
    handleDrop: function(view, event, slice, moved) {
      // we will do something here!
      return false; // not handled use default behaviour
    }
  },
  content: ...
});
```

I was thinking that maybe you could expose editorProps in the same way you expose extensions as a property, so I could configure the handleDrop function there and pass it in?

Thanks,
Geoff

**Comment by tgodkev** [comment]
@geoffkendall Did you ever find a work around for this?

**Comment by Bishwas-py** [comment]
Closing this for now, as of the new version, `0.0.7-up-5`. Feel free to reopen this.
