### ISSUE TITLE
Unable to resolve dependency tree

### ISSUE THREAD

**Issue by SA9102** [friendofsvelte/tipex#19]
I have an application that uses SvelteKit ^2.0.0 and Svelte ^4.2.7. When installing `@friendofsvelte/tipex`, I get an error saying that it's unable to resolve some dependencies:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: tipex-demo-4@0.0.1
npm ERR! Found: svelte@4.2.18
npm ERR! node_modules/svelte
npm ERR!   dev svelte@"^4.2.7" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer svelte@"^5.0.0-next.1" from @friendofsvelte/tipex@0.0.1-sv.5
npm ERR! node_modules/@friendofsvelte/tipex
npm ERR!   @friendofsvelte/tipex@"*" from the root project
```

Not quite able to make out exactly what the issue is, but I think it's to do with my version of Svelte. I think the package is looking for Svelte version ^5.0.0 but I'm using Svelte 4.

I'm able to get past this issue by using the `--legacy-peer-deps` flag, though this might not be a good solution for long term.

Alternatively, if I use Svelte 5, I don't need to use the flag and the package gets installed , but I get some peer dependency conflicts:

```
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: svelte-hmr@0.16.0
npm WARN Found: svelte@5.0.0-next.153
npm WARN node_modules/svelte
npm WARN   peer svelte@"^4.0.0 || ^5.0.0-next.0" from @sveltejs/kit@2.5.10
npm WARN   node_modules/@sveltejs/kit
npm WARN     peer @sveltejs/kit@"^2.0.0" from @sveltejs/adapter-auto@3.2.1
npm WARN     node_modules/@sveltejs/adapter-auto
npm WARN     1 more (the root project)
npm WARN   6 more (@sveltejs/vite-plugin-svelte, ...)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer svelte@"^3.19.0 || ^4.0.0" from svelte-hmr@0.16.0
npm WARN node_modules/@sveltejs/vite-plugin-svelte/node_modules/svelte-hmr
npm WARN   svelte-hmr@"^0.16.0" from @sveltejs/vite-plugin-svelte@3.1.1
npm WARN   node_modules/@sveltejs/vite-plugin-svelte
npm WARN
npm WARN Conflicting peer dependency: svelte@4.2.18
npm WARN node_modules/svelte
npm WARN   peer svelte@"^3.19.0 || ^4.0.0" from svelte-hmr@0.16.0
npm WARN   node_modules/@sveltejs/vite-plugin-svelte/node_modules/svelte-hmr
npm WARN     svelte-hmr@"^0.16.0" from @sveltejs/vite-plugin-svelte@3.1.1
npm WARN     node_modules/@sveltejs/vite-plugin-svelte
```

**Comment by Bishwas-py** [comment]
We are slowing transitioning towards svelte 5, so for this please you `npm install @friendofsvelte/tipex -f` for now. It'll work as expected.

**Comment by digitaldrreamer** [comment]
A workaround I used recently. Adding this to package.json:
```json
"overrides": {
    "@friendofsvelte/tipex": {
      "svelte": "$svelte"
    }
  }
```

It'll use the version of svelte that is currently installed in your project (denoted by $svelte), which is probably svelte 4 instead of the version specified in its own dependencies (svelte 5).

**Comment by Bishwas-py** [comment]
@digitaldrreamer tipex now fully supports `Svelte5`, you can try removing it from `"overrides"`, uninstall it, and reinstall it.

**Comment by Bishwas-py** [comment]
Happy to help!
