### ISSUE TITLE
How to disable the blue ring that comes when I click to edit on the editor?

### ISSUE THREAD

**Issue by robishx** [friendofsvelte/tipex#2]
Whenever I come to edit, there a blue ring on the text editor. I wanna disable it, or change the color of it how to do it?

**Comment by Bishwas-py** [comment]
To disable it you can simply pass a param `focusOnEdit="{false}"` it'll disable the `focusOnEdit`. Or you can also use `box-shadow: none;`. And to change the color, I'll update you on that.

**Comment by robishx** [comment]
Thanks `focusOnEdit="{false}"` did the work.
