### ISSUE TITLE
How to remove autofocus on mount?

### ISSUE THREAD

**Issue by FilipLjubic** [friendofsvelte/tipex#20]
Whenever I open the screen with the RTE, it scrolls down to it and auto focuses it. I can't find anything in the docs about it

**Comment by FilipLjubic** [comment]
nvm i got it working with, would have loved if this was more clearly documented

```svelte
	onMount(() => {
		$tipexEditor?.setOptions({
			autofocus: false
		});
	});
```

**Comment by Bishwas-py** [comment]
I'll consider that. Thanks
