### ISSUE TITLE
bind Editor Instance in Svelte 5

### ISSUE THREAD

**Issue by arnolicious** [friendofsvelte/tipex#24]
Hi there,
I can't seem to figure out how to get access to the editor instance in the svelte 5 version of this package.

Previous issues seemed to be solved by importing the `$tipexEditor` Store, however this does not seem to exist anymore.

And using `bind:this` binds to the actual `Tipex` Svelte Component, instead of the underlying Editor Instance, so I'm a little stumped.

**Comment by Bishwas-py** [comment]
Thank you so much for raising this issue. I am pushing a fix right now. In the meantime you could use.

```ts
const tipex = getContext('_tipex'); // or any id you passed in <Tipex ctxId='_tipex'
```

**Comment by Bishwas-py** [comment]
This commit fixes the issue: https://github.com/friendofsvelte/tipex/commit/9ff3de44adab9756b53f44921dacc45a0fbac8d9

Version: https://www.npmjs.com/package/@friendofsvelte/tipex/v/0.0.7-up-6

**Comment by Bishwas-py** [comment]
Assuming it worked for you. Lemme know, if there issue is persistant, we can reopen this.
