### ISSUE TITLE
enhancement: separate out toolbar and editor components

### ISSUE THREAD

**Issue by mateothegreat** [friendofsvelte/tipex#25]
Good work.. I've been tiptap'ing for a few months now and ended up writing my own wrapper but this looks promising!

I think it would be valuable to separate out the toolbar and the editor component so you can customize it (and then remove the fontawesome dependency too) to your needs.

We could then expose the tipex->tiptap->editor instance reference to call toggleItalic() etc.

Inspriation: https://github.com/infraregistry/app/blob/main/src/lib/components/editor/tiptap-editor/tiptap-editor-toolbar.svelte

**Comment by Bishwas-py** [comment]
I think it's already there. Can you please elaborate more?

**Comment by Bishwas-py** [comment]
Closing it, assuming it's resolved. Feel free to reopen!
