### ISSUE TITLE
Feat: Add examples using the htmlContent & onupdate

### ISSUE THREAD

**Issue by Jotenks66** [friendofsvelte/tipex#26]
Adding to the README some examples on how to retrieve the content of the editor.

**Comment by Bishwas-py** [comment]
Here:
- https://github.com/friendofsvelte/tipex?tab=readme-ov-file#how-to-get-html-content-from-editor
- https://github.com/friendofsvelte/tipex/blob/b27e38422f2db76c792d6217b7452b8514280f82/src/routes/%2Bpage.svelte#L18

**Comment by Bishwas-py** [comment]
Closing the issue, for now. Assuming this might have been resolved. Feel free to reopen!
