### ISSUE TITLE
Missing CSS when using the instructions

### ISSUE THREAD

**Issue by bluepuma77** [friendofsvelte/tipex#8]
When following the instructions with `npm install "@friendofsvelte/tipex"` and 

```
<script>
    import { Tipex } from "@friendofsvelte/tipex";
    import "@friendofsvelte/tipex/styles/Tipex.css";
    import "@friendofsvelte/tipex/styles/ProseMirror.css";
    import "@friendofsvelte/tipex/styles/Controls.css";
    import "@friendofsvelte/tipex/styles/EditLink.css";
    import "@friendofsvelte/tipex/styles/CodeBlock.css"; // for code block syntax highlighting

    let htmlContent = `
    <p>This <a target="_blank" rel="noopener noreferrer" href="">content</a> is written by
    <a target="_blank" rel="noopener noreferrer" href="http://bishwas.net/">Bishwas</a> in 2023.
    </p>`;
</script>

<Tipex
    {htmlContent}
    style="margin-top: 1rem; margin-bottom: 0rem;"
    class="h-[70vh] border border-neutral-200 dark:border-neutral-700 w-full"
/>
```
it seems there is some CSS missing, as the buttons are not next to each other:
<img width="450" alt="tipex-buttons" src="https://github.com/friendofsvelte/tipex/assets/5221187/a1ebff4b-69e9-4219-96ef-88dd3117f235">

What am I missing? Do I need Tailwind CSS?

**Comment by bluepuma77** [comment]
Stackblitz [link](https://stackblitz.com/edit/sveltejs-kit-template-default-z5z7jk?file=src%2Froutes%2F%2Bpage.svelte)

**Comment by Bishwas-py** [comment]
@bluepuma77 I am sorry, I got a little busy. Lemme have a look at it.

**Comment by Bishwas-py** [comment]
@bluepuma77 Try adding this into your script:
```
import "@friendofsvelte/tipex/styles/app.css";
```

**Comment by Bishwas-py** [comment]
We will remove that `app.css` to be imported, in the next version.

**Comment by Bishwas-py** [comment]
@bluepuma77 Docs updated, please have a look.

**Comment by bluepuma77** [comment]
Works with `import "@friendofsvelte/tipex/styles/app.css";`.
